make latest stable release

diff --git a/.github/workflows/python-script.yaml b/.github/workflows/python-script.yaml
--- a/.github/workflows/python-script.yaml
+++ b/.github/workflows/python-script.yaml
@@ -16,6 +16,8 @@ jobs:
   job1:
     name: Generate channel releases
     runs-on: ubuntu-latest
+    outputs:
+      STABLE_VERSION: ${{ steps.channel-collector.outputs.stable_version }}
     steps:
       - name: Checkout sources
         uses: actions/checkout@v4
@@ -56,6 +58,7 @@ jobs:
           cat ci/.helm/templates/configmap.yaml
       
       - name: Collect release versions
+        id: channel-collector
         run: python collect-released-versions.py
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -98,3 +101,53 @@ jobs:
           WERF_NAMESPACE: "deckhouse-web-dev"
           WERF_DIR: "channel-releases"
           WERF_DEV: "true"
+  job3:
+    name: Update 
+    runs-on: ubuntu-latest
+    needs: job1
+    steps:
+
+      - name: Make latest stable release
+        env:
+          STABLE_VERSION: ${{ needs.job1.outputs.STABLE_VERSION }}
+        run: |
+          set -e
+
+          url="https://api.github.com"
+
+          owner="${GITHUB_REPOSITORY%/*}"
+          repo="${GITHUB_REPOSITORY#*/}"
+
+          release_by_tag="${url}/repos/${GITHUB_REPOSITORY}/releases/tags/${STABLE_VERSION}"
+
+          echo "${owner}"
+          echo "${repo}"
+          # echo $release_by_tag
+          response=$(curl -s -w "\n%{http_code}" -X GET ${release_by_tag} \
+              -H "Authorization: Bearer ${GITHUB_TOKEN}") || exit $?
+
+          response_code=$(echo "$response" | tail -n1)
+
+          if [[ $response_code != '200' ]]; then
+              echo -e "\e[31mERROR: Unable to determinate release id by tag!\e[0m"
+              exit 1
+          fi
+
+          release_id=$(echo "$response" | sed  '$d' | jq ".id")
+          release_name=$(echo "$response" | sed  '$d' | jq ".name")
+          echo $release_id
+
+          update_release="${url}/repos/${GITHUB_REPOSITORY}/releases/${release_id}"
+
+          response=$(curl -s -w "\n%{http_code}" -X PATCH ${update_release} \
+              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+              -d '{"prerelease":false,"make_latest":true}') || exit $?
+
+          response_code=$(echo "$response" | tail -n1)
+
+          if [[ $response_code != '200' ]]; then
+              echo -e "\e[31mERROR: Unable to update release ${release_name}!\e[0m"
+              exit 1
+          fi
+
+          echo -e "\e[32mRelease \"${release_name}\" has been successfully marked as latest."
